CREATE TABLE `Survey` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `Name` varchar(255) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

CREATE TABLE `SurveyItems` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `Name` varchar(255) NOT NULL,
 `SurveyID` int(11) NOT NULL,
 PRIMARY KEY (`ID`),
 KEY `SurveyID` (`SurveyID`),
 CONSTRAINT `SurveyItems_ibfk_2` FOREIGN KEY (`SurveyID`) REFERENCES `Survey` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

CREATE TABLE `SurveyAnswer` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `TimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `SurveyItemID` int(11) NOT NULL,
 PRIMARY KEY (`ID`),
 KEY `SurveyItemID` (`SurveyItemID`),
 CONSTRAINT `SurveyAnswer_ibfk_2` FOREIGN KEY (`SurveyItemID`) REFERENCES `SurveyItems` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

CREATE TABLE `User` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `Name` varchar(64) NOT NULL,
 `Passwort` varchar(64) NOT NULL,
 `LastLogIn` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `Name` (`Name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;